# Generated by Django 2.2.1 on 2019-05-06 14:21

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AadharCardDeatils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(blank=True, null=True, upload_to='aadhar/%Y/%m/%D/')),
            ],
        ),
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalQualifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GradingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading_system_name', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('mobile_number', models.BigIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Majors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.TextField(blank=True)),
                ('qualification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='job_seeker.EducationalQualifications')),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium_name', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.TextField()),
                ('verification_id', models.CharField(max_length=320)),
                ('otp', models.IntegerField()),
                ('otp_status', models.CharField(max_length=1)),
                ('timestamp', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_set_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniversitiesInstitutesMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute', to='job_seeker.Institutes')),
                ('university_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university', to='job_seeker.Universities')),
            ],
        ),
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_name', models.TextField(blank=True)),
                ('majors_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='job_seeker.Majors')),
            ],
        ),
        migrations.CreateModel(
            name='SeekerSkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_set_name_id', to='job_seeker.SkillSet')),
                ('user_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_account_skill_id', to='employer.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='SeekerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_salary', models.IntegerField(null=True)),
                ('is_annually_monthly', models.BooleanField(default=0)),
                ('is_fresher', models.BooleanField(default=0)),
                ('currency', models.CharField(max_length=50, null=True)),
                ('resume_document1', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%D/')),
                ('resume_video1', models.FileField(blank=True, null=True, upload_to='video/%Y/%m/%D/')),
                ('resume_document2', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%D/')),
                ('resume_video2', models.FileField(blank=True, null=True, upload_to='video/%Y/%m/%D/')),
                ('notice_period', models.CharField(max_length=20, null=True)),
                ('break_reason', models.CharField(max_length=50, null=True)),
                ('break_duration', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=1000, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('martial_status', models.CharField(max_length=20, null=True)),
                ('differently_abled', django_mysql.models.JSONField(default='{}')),
                ('work_permit_usa', models.CharField(max_length=40, null=True)),
                ('work_permit_other', models.CharField(max_length=100, null=True)),
                ('desired_career_profile', django_mysql.models.JSONField(default='{}')),
                ('aadhar_url', models.CharField(max_length=400, null=True)),
                ('user_account_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account_seeker_id', to='employer.UserAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperienceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current_job', models.BooleanField(default=0)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('description', models.TextField(null=True)),
                ('annual_salary', models.BigIntegerField(null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_city', to='job_seeker.Location')),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='job_seeker.CompanyNames')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_country', to='job_seeker.Location')),
                ('job_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation', to='job_seeker.Designation')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_state', to='job_seeker.Location')),
                ('user_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_account_exp_id', to='employer.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True)),
                ('completion_date', models.DateTimeField(null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passed_out_year', models.CharField(max_length=10, null=True)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board', to='job_seeker.Boards')),
                ('degree_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degree', to='job_seeker.EducationalQualifications')),
                ('grading_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grading_system_edu_id', to='job_seeker.GradingSystem')),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insitute', to='job_seeker.Institutes')),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major', to='job_seeker.Majors')),
                ('medium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediums', to='job_seeker.Medium')),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialization', to='job_seeker.Specializations')),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='job_seeker.Universities')),
                ('user_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_account_edu_id', to='employer.UserAccount')),
            ],
        ),
    ]
