# Generated by Django 2.2.1 on 2019-05-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='resume_headline',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
