# Generated by Django 2.2.1 on 2019-05-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0005_seekerprofile_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='profile_summery',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
