# Generated by Django 2.2.1 on 2019-05-27 15:36

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0006_seekerprofile_profile_summery'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='client',
            field=django_mysql.models.JSONField(default='{}'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='details_of_project',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='project_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='role',
            field=django_mysql.models.JSONField(default='{}'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='role_description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
