# Generated by Django 2.2.1 on 2019-05-06 14:21

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import partial_date.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiseCompanyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_description', models.CharField(max_length=300, null=True)),
                ('website_url', models.TextField(null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('contact_number', models.CharField(max_length=15, null=True)),
                ('contact_person', models.CharField(max_length=255, null=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='company_details/%Y/%m/%D/')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertiseCompanyDetailsJobMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertiseCompanyDetailsUserMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.CharField(max_length=10, null=True)),
                ('pan_file_path', models.FileField(blank=True, null=True, upload_to='documnets/%Y/%m/%D/')),
                ('other_file_path', models.FileField(blank=True, null=True, upload_to='documnets/%Y/%m/%D/')),
                ('is_company_verified', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=3, null=True)),
                ('symbol', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=50, null=True)),
                ('is_admin', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesireCandidateProfileSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('mobile_number', models.BigIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='documnets/%Y/%m/%D/')),
                ('document_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerIndustriesMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.CharField(max_length=255, null=True)),
                ('linkedin_url', models.CharField(max_length=255, null=True)),
                ('business_email', models.EmailField(max_length=329, null=True)),
                ('is_business_email_verified', models.BooleanField(default=0)),
                ('secondary_email', models.EmailField(max_length=329, null=True)),
                ('profile_headline', models.CharField(max_length=300, null=True)),
                ('permissions', models.TextField(null=True)),
                ('is_admin', models.BooleanField(default=0)),
                ('suspended_date', models.BigIntegerField(null=True)),
                ('suspended_till', models.DateField(null=True)),
                ('customize_profile_url', models.CharField(max_length=30, null=True)),
                ('about_employer', models.CharField(max_length=30, null=True)),
                ('employer_profile_status', models.CharField(max_length=30, null=True)),
                ('created_on', models.BigIntegerField(null=True)),
                ('updated_on', models.BigIntegerField(null=True)),
                ('reason', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerWorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, null=True)),
                ('is_current_job', models.BooleanField(default=True)),
                ('start_date', partial_date.fields.PartialDateField(null=True)),
                ('end_date', partial_date.fields.PartialDateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FunctionalAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Industries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InputType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='JobPostQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='JobRequiredPHDQualifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='JobRequiredQualifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LevelIHire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OptionValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PostJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=1000, null=True)),
                ('job_description', models.CharField(max_length=900, null=True)),
                ('min_experience', models.IntegerField(null=True)),
                ('max_experience', models.IntegerField(null=True)),
                ('is_fresher', models.BooleanField(default=0)),
                ('min_salary', models.CharField(max_length=45, null=True)),
                ('max_salary', models.CharField(max_length=45, null=True)),
                ('is_salary_visible', models.BooleanField(default=0)),
                ('no_of_vacancies', models.IntegerField(null=True)),
                ('how_soon_required', models.CharField(max_length=100, null=True)),
                ('type_of_job', django_mysql.models.EnumField(choices=[('Part time', 'Part time'), ('Full time', 'Full time'), ('Part-time work from home', 'Part-time work from home'), ('Full-time work from home', 'Full-time work from home'), ('Freelancer', 'Freelancer')], null=True)),
                ('is_longtime_break', models.BooleanField(default=0)),
                ('reference_code', models.CharField(max_length=10, null=True)),
                ('is_email_response', models.BooleanField(default=1)),
                ('is_email_forward', models.BooleanField(default=0)),
                ('forward_email_id', models.CharField(max_length=320, null=True)),
                ('schedule_time', django_mysql.models.EnumField(choices=[('Week', 'Week'), ('Fortnight', 'Fortnight'), ('Month', 'Month')], null=True)),
                ('status', django_mysql.models.EnumField(choices=[('Post', 'Post'), ('Draft', 'Draft'), ('Save', 'Save')], null=True)),
                ('hire_for', models.CharField(max_length=45, null=True)),
                ('from_count', models.IntegerField(null=True)),
                ('is_phd_premium_university', models.BooleanField(default=0)),
                ('is_graduate_premium_university', models.BooleanField(default=0)),
                ('candidate_profile', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_job_post', to='employer.Currency')),
                ('functional_area_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functional_area_id_post', to='employer.FunctionalAreas')),
                ('industries_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='industry_id_post', to='employer.Industries')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100, null=True)),
                ('is_mandatory', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('email_id', models.EmailField(max_length=320)),
                ('country_code', models.IntegerField(default=91)),
                ('mobile_number', models.CharField(max_length=15, null=True)),
                ('dob', models.DateField(null=True)),
                ('password', models.CharField(max_length=200)),
                ('regestration_date', models.BigIntegerField(null=True)),
                ('profile_image_path', models.FileField(blank=True, null=True, upload_to='profile/%Y/%m/%D/')),
                ('address', models.CharField(max_length=255, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('is_employer', models.BooleanField(default=0)),
                ('is_job_seeker', models.BooleanField(default=0)),
                ('is_sms_notification_active', models.BooleanField(default=0)),
                ('is_email_notification_active', models.BooleanField(default=0)),
                ('is_account_approved', models.BooleanField(default=0)),
                ('is_email_verified', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_type', models.CharField(max_length=45, null=True)),
                ('start_time', models.CharField(max_length=50, null=True)),
                ('end_time', models.CharField(max_length=50, null=True)),
                ('job_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_id_time', to='employer.PostJobs')),
            ],
        ),
        migrations.CreateModel(
            name='WalkinDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('venue', models.TextField(null=True)),
                ('location_url', models.TextField(null=True)),
                ('job_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_id_walkin', to='employer.PostJobs')),
            ],
        ),
        migrations.CreateModel(
            name='UserLinkedinDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=1000, null=True)),
                ('refresh_token', models.CharField(max_length=1000, null=True)),
                ('profile_pic_url', models.CharField(max_length=1000, null=True)),
                ('user_account_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account_id_linkedin', to='employer.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='UserGmailLoginDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=1000, null=True)),
                ('refresh_token', models.CharField(max_length=1000, null=True)),
                ('profile_pic_url', models.CharField(max_length=1000, null=True)),
                ('user_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_account_id_gmail', to='employer.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='ShowOrHideOrganisations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=0)),
                ('job_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_id_hide_or_show', to='employer.PostJobs')),
                ('organisation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_id_show_or_hide', to='employer.Organizations')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOptionsMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_type_id', to='employer.InputType')),
                ('option_values_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options_value_id', to='employer.OptionValues')),
                ('question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_id1', to='employer.Questions')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_id', to='employer.Questions')),
                ('questionnaire_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_id_questions', to='employer.Questionnaire')),
            ],
        ),
    ]
