# Generated by Django 2.2.1 on 2019-05-06 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_seeker', '0001_initial'),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjobs',
            name='job_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations_id_post', to='job_seeker.Designation'),
        ),
        migrations.AddField(
            model_name='postjobs',
            name='user_account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account_id_post', to='employer.UserAccount'),
        ),
        migrations.AddField(
            model_name='jobrequiredqualifications',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_id_qualification1', to='employer.PostJobs'),
        ),
        migrations.AddField(
            model_name='jobrequiredqualifications',
            name='major_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major_id_qualification1', to='job_seeker.Majors'),
        ),
        migrations.AddField(
            model_name='jobrequiredqualifications',
            name='specialization_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialization_id_qualification1', to='job_seeker.Specializations'),
        ),
        migrations.AddField(
            model_name='jobrequiredphdqualifications',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_id_qualification2', to='employer.PostJobs'),
        ),
        migrations.AddField(
            model_name='jobrequiredphdqualifications',
            name='phd_major_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major_id_qualification2', to='job_seeker.Majors'),
        ),
        migrations.AddField(
            model_name='jobrequiredphdqualifications',
            name='phd_specialization_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialization_id_qualification2', to='job_seeker.Specializations'),
        ),
        migrations.AddField(
            model_name='jobpostquestionnaire',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_id_post_questionnaire', to='employer.PostJobs'),
        ),
        migrations.AddField(
            model_name='jobpostquestionnaire',
            name='questionnaire_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_id', to='employer.Questionnaire'),
        ),
        migrations.AddField(
            model_name='jobpostquestionnaire',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='employer.UserAccount'),
        ),
        migrations.AddField(
            model_name='joblocations',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_id_city', to='job_seeker.Location'),
        ),
        migrations.AddField(
            model_name='joblocations',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_id_country', to='job_seeker.Location'),
        ),
        migrations.AddField(
            model_name='joblocations',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_id_location', to='employer.PostJobs'),
        ),
        migrations.AddField(
            model_name='employerworkexperience',
            name='designation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation_id1', to='job_seeker.Designation'),
        ),
        migrations.AddField(
            model_name='employerworkexperience',
            name='organization_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations_id1', to='employer.Organizations'),
        ),
        migrations.AddField(
            model_name='employerworkexperience',
            name='user_account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_account_id_work_experience', to='employer.UserAccount'),
        ),
        migrations.AddField(
            model_name='employerquestionnaire',
            name='questionnaire_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_id2', to='employer.Questionnaire'),
        ),
        migrations.AddField(
            model_name='employerquestionnaire',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id2', to='employer.UserAccount'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_details_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_company_details_id', to='employer.CompanyDetails'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='current_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_city_id', to='job_seeker.Location'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='current_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_country_id', to='job_seeker.Location'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='designation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation_id', to='job_seeker.Designation'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='organization_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations_id', to='employer.Organizations'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_id', to='employer.UserAccount'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='user_account_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account_id_profile', to='employer.UserAccount'),
        ),
        migrations.AddField(
            model_name='employerindustriesmapping',
            name='industries_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='industries_employer_industries_mapping_id', to='employer.Industries'),
        ),
        migrations.AddField(
            model_name='employerindustriesmapping',
            name='user_account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account_employer_industries_mapping_id', to='employer.UserAccount'),
        ),
        migrations.AddField(
            model_name='employerdocuments',
            name='user_account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_account_id_documents', to='employer.UserAccount'),
        ),
        migrations.AddField(
            model_name='desirecandidateprofileskills',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_id_skill', to='employer.PostJobs'),
        ),
        migrations.AddField(
            model_name='desirecandidateprofileskills',
            name='qualities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_id_skillset', to='job_seeker.SkillSet'),
        ),
        migrations.AddField(
            model_name='advertisecompanydetailsusermapping',
            name='advertise_company_details_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertise_company_details_user_map', to='employer.AdvertiseCompanyDetails'),
        ),
        migrations.AddField(
            model_name='advertisecompanydetailsusermapping',
            name='user_account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account_advertise_id', to='employer.UserAccount'),
        ),
        migrations.AddField(
            model_name='advertisecompanydetailsjobmapping',
            name='advertise_company_details_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertise_company_details_job_map', to='employer.AdvertiseCompanyDetails'),
        ),
        migrations.AddField(
            model_name='advertisecompanydetailsjobmapping',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_jobs_advertise_id', to='employer.PostJobs'),
        ),
        migrations.AddField(
            model_name='advertisecompanydetails',
            name='organisation_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_id_advertise', to='employer.Organizations'),
        ),
    ]
