# Generated by Django 2.2.1 on 2019-05-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_auto_20190506_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='middle_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
